version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: smart_soil
      POSTGRES_USER: smart_soil_user
      POSTGRES_PASSWORD: P@$$w0rD
    networks:
      - backend

  web:
    build: .
    command:
      - bash
      - -c
      - |
        python manage.py collectstatic --noinput
        python manage.py makemigrations  --merge --noinput
        python manage.py migrate
        python manage.py runserver 0.0.0.0:9001
    volumes:
      - .:/web
    ports:
      - "9001:9001"
    depends_on:
      - db
    environment:
      DATABASE_NAME: smart_soil
      DATABASE_USER: smart_soil_user
      DATABASE_PASSWORD: P@$$w0rD
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
