# Generated by Django 4.2.1 on 2024-06-11 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('devices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='device.device')),
            ],
        ),
    ]
