# Generated by Django 4.2.1 on 2024-06-11 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_device_id_zone_id_alter_device_device_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sensor_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('sensor_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='sensors',
            field=models.ForeignKey(default='sensor_1', on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='device.sensor'),
            preserve_default=False,
        ),
    ]
