# Generated by Django 4.2.1 on 2024-06-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_sensor_device_sensors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='value',
        ),
        migrations.AddField(
            model_name='sensor',
            name='value',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
