# Generated by Django 4.2.1 on 2024-06-26 14:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_alter_sensorhistory_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorhistory',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
