# Generated by Django 4.2.1 on 2024-06-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_remove_device_value_sensor_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombinedView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Combined View',
                'verbose_name_plural': 'Combined Views',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
