# Generated by Django 4.2.1 on 2024-06-12 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_combinedview_alter_sensor_sensor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='sensors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='device.sensor'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='devices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zones', to='device.device'),
        ),
    ]
