# Generated by Django 4.2.1 on 2024-06-12 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_alter_device_sensors_alter_zone_devices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='sensors',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='devices', to='device.sensor'),
        ),
    ]
