# Generated by Django 4.2.1 on 2024-06-12 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0007_alter_device_sensors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='sensors',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='devices', to='device.sensor'),
        ),
    ]
