# Generated by Django 4.2.1 on 2024-06-12 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0009_alter_device_sensors_alter_zone_devices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='sensors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='device.sensor'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='devices',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='device.device'),
        ),
    ]
